### ISSUE TITLE
Slower than cpu?

### ISSUE THREAD

**Issue by peerajak** [forresti/convolution#1]
Dear Foresti,

I tested your code and found that it is atleast 10 times slower than CPU version I am using. I admit I don't understand "amount to load" and the correct (meaning fast) method to input my own conv filters. What I did I just cuda memcpy my 6 filters to your convolutional fn and cal the result.  The result seems correct but it is slower than CPU, 10 times.  Please advice.  I can give my code for your testing. I am testing it as mex file.

**Comment by forresti** [comment]
Sure, I'd be happy to take a look. Post your code here or send it to me?
(forresti@eecs.berkeley.edu)

**Comment by peerajak** [comment]
Hi forresti

Last time we talk, I said may be Caffe could be a good convolution implementation. I found that Caffe rounding precision is not accurate. It has an error around 7th decimal place. I don't know if your GPU convolution has better rounding precision accuracy?
